MainBundle\Entity\Actor:
    type: entity
    table: null
    repositoryClass: MainBundle\Repository\ActorRepository
    id:
        id:
            type: uuid
            id: true
            generator:
                strategy: CUSTOM
            customIdGenerator:
                class: Ramsey\Uuid\Doctrine\UuidGenerator
    fields:
        name:
            type: string
            length: '255'
        picture:
            type: string
            length: '255'
    oneToMany:
        serieActors:
            targetEntity: MainBundle\Entity\SerieActor
            mappedBy: actor
    lifecycleCallbacks: {  }
