MainBundle\Entity\Critic:
    type: entity
    table: null
    repositoryClass: MainBundle\Repository\CriticRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        score:
            type: float
        content:
            type: text
        likeNumber:
            type: integer
        dislikeNumber:
            type: integer
        title:
            type: string
            length: '255'
        postedThe:
            type: datetime
        isValid:
            type: boolean
    manyToOne:
        serie:
            targetEntity: MainBundle\Entity\Serie
            inversedBy: critics
        user:
            targetEntity: MainBundle\Entity\User
            inversedBy: critics
    lifecycleCallbacks: {  }
