MainBundle\Entity\CriticNotation:
    type: entity
    table: null
    repositoryClass: MainBundle\Repository\CriticNotationRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        isLike:
            type: boolean
    manyToOne:
        critic:
            targetEntity: MainBundle\Entity\Critic
            inversedBy: criticNotations
        user:
            targetEntity: MainBundle\Entity\User
            inversedBy: criticNotations
    lifecycleCallbacks: {  }
