MainBundle\Entity\Episode:
    type: entity
    table: null
    repositoryClass: MainBundle\Repository\EpisodeRepository
    id:
        id:
            type: uuid
            id: true
            generator:
                strategy: CUSTOM
            customIdGenerator:
                class: Ramsey\Uuid\Doctrine\UuidGenerator
    fields:
        title:
            type: string
            length: '50'
        description:
            type: text
        episodeNumber:
            type: string
            length: '15'
    manyToOne:
        serie:
            targetEntity: MainBundle\Entity\Serie
            inversedBy: episodes
    lifecycleCallbacks: {  }
