MainBundle\Entity\Favoris:
    type: entity
    table: null
    repositoryClass: MainBundle\Repository\FavorisRepository
    id:
        id:
            type: uuid
            id: true
            generator:
                strategy: CUSTOM
            customIdGenerator:
                class: Ramsey\Uuid\Doctrine\UuidGenerator
    manyToOne:
        user:
            targetEntity: MainBundle\Entity\User
            inversedBy: favoris
        serie:
            targetEntity: MainBundle\Entity\Serie
            inversedBy: favoris
    lifecycleCallbacks: {  }
