MainBundle\Entity\SerieTypeTemp:
    type: entity
    table: null
    repositoryClass: MainBundle\Repository\SerieTypeTempRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToOne:
        type:
            targetEntity: MainBundle\Entity\Type
            inversedBy: serieTypeTemps
        serieTemp:
            targetEntity: MainBundle\Entity\SerieTemp
            inversedBy: serieTypeTemps
    lifecycleCallbacks: {  }
