MainBundle\Entity\SerieType:
    type: entity
    table: null
    repositoryClass: MainBundle\Repository\SerieTypeRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToOne:
        type:
            targetEntity: MainBundle\Entity\Type
            inversedBy: serieTypes
        serie:
            targetEntity: MainBundle\Entity\Serie
            inversedBy: serieTypes
    lifecycleCallbacks: {  }
