MainBundle\Entity\SerieType:
    type: entity
    table: null
    repositoryClass: MainBundle\Repository\SerieTypeRepository
    id:
        id:
            type: uuid
            id: true
            generator:
                strategy: CUSTOM
            customIdGenerator:
                class: Ramsey\Uuid\Doctrine\UuidGenerator
    fields:
        creationDate:
            type: datetime
        modificationDate:
            type: datetime
    manyToOne:
        type:
            targetEntity: MainBundle\Entity\Type
            inversedBy: serieTypes
        serie:
            targetEntity: MainBundle\Entity\Serie
            inversedBy: serieTypes
    lifecycleCallbacks: {  }
