MainBundle\Entity\SerieTemp:
    type: entity
    table: null
    repositoryClass: MainBundle\Repository\SerieTempRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: '50'
        description:
            type: text
        poster:
            type: string
            length: 255
    manyToOne:
        serie:
            targetEntity: MainBundle\Entity\Serie
            inversedBy: serieTemps
    oneToMany:
        serieTypeTemps:
            targetEntity: MainBundle\Entity\SerieTypeTemp
            mappedBy: serieTemp
        serieActorTemps:
            targetEntity: MainBundle\Entity\SerieActorTemp
            mappedBy: serieTemp
    lifecycleCallbacks: {  }
