MainBundle\Entity\SerieActorTemp:
    type: entity
    table: null
    repositoryClass: MainBundle\Repository\SerieActorTempRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        role:
            type: string
            length: '25'
    manyToOne:
        actor:
            targetEntity: MainBundle\Entity\Actor
            inversedBy: serieActorTemps
        serieTemp:
            targetEntity: MainBundle\Entity\SerieTemp
            inversedBy: serieActorTemps
    lifecycleCallbacks: {  }
