MainBundle\Entity\Type:
    type: entity
    table: null
    repositoryClass: MainBundle\Repository\TypeRepository
    id:
        id:
            type: uuid
            id: true
            generator:
                strategy: CUSTOM
            customIdGenerator:
                class: Ramsey\Uuid\Doctrine\UuidGenerator
    fields:
        name:
            type: string
            length: '25'
    oneToMany:
        serieTypes:
            targetEntity: MainBundle\Entity\SerieType
            mappedBy: type
    lifecycleCallbacks: {  }
