MainBundle\Entity\User:
    type: entity
    table: fos_user
    repositoryClass: MainBundle\Repository\UserRepository
    id:
        id:
            type: uuid
            id: true
            generator:
                strategy: CUSTOM
            customIdGenerator:
                class: Ramsey\Uuid\Doctrine\UuidGenerator
    fields:
        lastName:
            type: string
            length: '255'
        firstName:
            type: string
            length: '255'
        userName:
            type: string
            length: '255'
        mail:
            type: string
            length: '255'
            unique: true
        birthdate:
            type: datetime
        profilePicture:
            type: string
            length: '255'
        criticNumber:
            type: integer
        isModo:
            type: boolean
        isAdmin:
            type: boolean
        isValid:
            type: boolean
    oneToMany:
        critics:
            targetEntity: MainBundle\Entity\Critic
            mappedBy: user
        favoris:
            targetEntity: MainBundle\Entity\Favoris
            mappedBy: user
        criticNotations:
            targetEntity: MainBundle\Entity\CriticNotation
            mappedBy: user
    lifecycleCallbacks: {  }
