# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_USER:        ROLE_USER
        ROLE_ADMIN:       ROLE_MODO
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                login_path: /en
                check_path: fos_user_security_check
                provider: fos_userbundle
                always_use_default_target_path : true
                default_target_path: /en/wall
                use_referer : true
                csrf_token_generator: security.csrf.token_manager # Use form.csrf_provider instead for Symfony <2.4
            logout:
                path: /en/logout
                target: /en
            anonymous:    true

    access_control:
        - { path: ^/(en|fr)/serie/*, role: ROLE_USER }
        - { path: ^/(en|fr)/admin/*, role: ROLE_ADMIN }
        - { path: ^/(en|fr)/favoris/*, role: ROLE_USER }
        - { path: ^/(en|fr)/favoris, role: ROLE_USER }
        - { path: ^/(en|fr)/unwall, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(en|fr)/legal, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(en|fr)/wall, role: ROLE_USER }
        - { path: ^/(en|fr)/search, role: ROLE_USER }
        - { path: ^/(en|fr)/account, role: ROLE_USER }
        - { path: ^/(en|fr), role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }



#security:
#
#    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
#    providers:
#        in_memory:
#            memory: ~
#
#    firewalls:
#        # disables authentication for assets and the profiler, adapt it according to your needs
#        dev:
#            pattern: ^/(_(profiler|wdt)|css|images|js)/
#            security: false
#
#        main:
#            anonymous: ~
#            # activate different ways to authenticate
#
#            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
#            #http_basic: ~
#
#            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
#            #form_login: ~
