# Route pour les séries

serie_search:
    path: /
    defaults:
        _controller: MainBundle:Serie:search

serie_add:
    path: /add
    defaults:
        _controller: MainBundle:Serie:add

serie_show:
    path: /{idSerie}
    defaults:
        _controller: MainBundle:Serie:show
    requirements:
        idSerie: \d+

serie_update:
    path: /{idSerie}/update
    defaults:
        _controller: MainBundle:Serie:update
    requirements:
        idSerie: \d+

serie_delete:
    path: /{idSerie}/delete
    defaults:
        _controller: MainBundle:Serie:delete
    requirements:
        idSerie: \d+

# Route pour les épisodes

serie_show_episode:
    path: /{idSerie}/{idEpisode}
    defaults:
        _controller: MainBundle:Episode:show
    requirements:
        idSerie: \d+
        idEpisode: \d+

serie_add_episode:
    path: /{idSerie}/{idEpisode}/add
    defaults:
        _controller: MainBunde:Episode:add
    requirements:
        idSerie: \d+
        idEpisode: \d+

serie_update_episode:
    path: /{idSerie}/{idEpisode}/update
    defaults:
        _controller: MainBundle:Episode:update
    requirements:
        idSerie: \d+
        idEpisode: \d+

serie_delete_episode:
    path: /{idSerie}/{idEpisode}/delete
    defaults:
        _controller: MainBundle:Episode:delete
    requirements:
        idSerie: \d+
        idEpisode: \d+