<?php

namespace MainBundle\Repository;

/**
 * CriticRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CriticRepository extends \Doctrine\ORM\EntityRepository
{
    // Récupère les dernières critique publier qui sont valider
    public function getLastUploadedAndValidatedCritics() {}

    // Supprime une critique
    public function deleteCritic($criticId) {}

    // Valide une critique
    public function validCritic($criticId) {}
}
