<?php

namespace MainBundle\Repository;

/**
 * CriticRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CriticRepository extends \Doctrine\ORM\EntityRepository
{
    // Récupère les dernière critique publier qui sont valider
    public function getLastUploadeAndValidatedCritics() {}
}
