<?php

namespace MainBundle\Repository;

/**
 * CriticNotationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CriticNotationRepository extends \Doctrine\ORM\EntityRepository
{
}
