<?php

namespace MainBundle\Repository;

use MainBundle\Entity\Favoris;

/**
 * FavorisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FavorisRepository extends \Doctrine\ORM\EntityRepository
{
    // Récupère les favoris d'un utilisateur
    public function getFavorisByUserId($userId)
    {
        $user = $this->getEntityManager()->getRepository("MainBundle:User")->getUserById($userId);

        return $this->getEntityManager()->createQueryBuilder()
            ->select("f")
            ->from("MainBundle:Favoris", "f")
            ->where("f.user = :user")
            ->setParameter(":user", $user)
            ->getQuery()->getResult();
    }

    // Ajout d'une série au favoris
    public function addSerie($userId, $serieId)
    {
        $favoris = new Favoris();
        $favoris->setUser($userId)->setSerie($serieId);

        $this->getEntityManager()->persist($favoris);
        $this->getEntityManager()->flush();
    }

    // Retirer la série des favoris
    public function removeFavoris($favorisId)
    {
        $fav = $this->findOneBy($favorisId);

        $this->getEntityManager()->remove($fav);
        $this->getEntityManager()->flush();
    }
}
