<?php

namespace MainBundle\Repository;

/**
 * SerieActorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SerieActorRepository extends \Doctrine\ORM\EntityRepository
{
    public function getActorBySerieId($serieId)
    {
        $serie = $this->getEntityManager()
            ->getRepository("MainBundle:Serie")->getSerieWithId($serieId);

        $serieActors = $this->findBy(["serie" => $serie]);

        $Actors = [];

        foreach($serieActors as $serieActor)
        {
            $Actors[] = [$serieActor->getActor()->getName(), $serieActor->getRole()];
        }

        return $Actors;
    }
}
