<?php

namespace MainBundle\Repository;

/**
 * SerieActorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SerieActorRepository extends \Doctrine\ORM\EntityRepository
{
}
