<?php

namespace MainBundle\Repository;

/**
 * SerieActorTempRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SerieActorTempRepository extends \Doctrine\ORM\EntityRepository
{
}
