<?php

namespace MainBundle\Repository;

/**
 * SerieTempRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SerieTempRepository extends \Doctrine\ORM\EntityRepository
{
}
