<?php

namespace MainBundle\Repository;

/**
 * SerieTypeTempRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SerieTypeTempRepository extends \Doctrine\ORM\EntityRepository
{
}
