<?php

namespace MainBundle\Repository;

/**
 * SerieTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SerieTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
