<?php

namespace MainBundle\Repository;

/**
 * TypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeRepository extends \Doctrine\ORM\EntityRepository
{
    public function getTypes()
    {
        return $this->findAll();
    }

    public function getTypeById($typeId)
    {
        return $this->findOneBy(["id" => $typeId]);
    }

    public function getTypesOrderByNameASC()
    {
        return $this->getEntityManager()->createQueryBuilder()
            ->select("t")
            ->from("MainBundle:Type", "t")
            ->orderBy("t.name", "ASC")
            ->getQuery()
            ->getResult();
    }

    public function checkIfTypeAlreadyHere($typeName)
    {
        $isHereOrNot = $this->getEntityManager()->createQueryBuilder()
            ->select("t")
            ->from("MainBundle:Type", "t")
            ->where("t.name = :tName")
            ->setParameter(":tName", $typeName)
            ->getQuery()
            ->getResult();


        if(count($isHereOrNot))
            return false;

        return true;
    }

    public function getTypeByName($typeName)
    {
        return $this->findBy(['name' => $typeName]);
    }

    public function getOneTypeByName($typeName)
    {
        return $this->findOneBy(["name" => $typeName]);
    }
}
