main_home:
    path:     /
    defaults:
        _controller: MainBundle:Main:home

main_wall:
    path:     /wall
    defaults:
        _controller: MainBundle:Main:wall

main_favoris:
    path:     /favoris
    defaults:
        _controller: MainBundle:Main:favoris

main_serie:
    path:   /serie
    defaults:
        _controller: MainBundle:Main:serie

admin:
    resource: "routing/admin.yml"
    prefix: /admin