main_home:
    path:     /{_locale}
    defaults:
        _controller: MainBundle:Main:home
    requirements:
        _locale: en|fr

main_wall:
    path:     /{_locale}/wall
    defaults:
        _controller: MainBundle:Main:wall
    requirements:
        _locale: en|fr

main_unloggedWall:
    path:     /{_locale}/unWall
    defaults:
        _controller: MainBundle:Main:unloggedWall
    requirements:
        _locale: en|fr

main_search:
    path:     /{_locale}/search
    defaults:
        _controller: MainBundle:Main:search
    requirements:
        _locale: en|fr

main_favoris:
    path:     /{_locale}/favoris
    defaults:
        _controller: MainBundle:Main:favoris
    requirements:
        _locale: en|fr

main_add_favoris:
   path:     /{_locale}/favoris/{idSerie}
   defaults:
       _controller: MainBundle:Main:favoris
   requirements:
       _locale: en|fr

main_serie:
    path:     /{_locale}/serie/{idSerie}
    defaults:
        _controller: MainBundle:Main:serie
    requirements:
        idSerie: '[a-zA-Z-0-9]{36}'
        _locale: en|fr

main_episode:
    path:     /{_locale}/serie/{idSerie}/episode/{idEpisode}
    defaults:
        _controller: MainBundle:Main:episode
    requirements:
        idSerie: '[a-zA-Z-0-9]{36}'
        idEpisode: '[a-zA-Z-0-9]{36}'
        _locale: en|fr

main_account:
    path:     /{_locale}/account
    defaults:
        _controller: MainBundle:Main:account
    requirements:
        _locale: en|fr

main_legal:
    path:     /{_locale}/legal
    defaults:
        _controller: MainBundle:Main:legal
    requirements:
        _locale: en|fr

admin_modifSerie:
    path:     /{_locale}/admin/modifSerie
    defaults:
        _controller: MainBundle:Admin:modifSerie
    requirements:
        _locale: en|fr

admin_submitSerie:
    path:     /{_locale}/admin/submitSerie
    defaults:
        _controller: MainBundle:Admin:submitSerie
    requirements:
        _locale: en|fr

admin_validCritic:
    path:     /{_locale}/admin/validCritic
    defaults:
        _controller: MainBundle:Admin:validCritic
    requirements:
        _locale: en|fr

admin_userManager:
    path:     /{_locale}/admin/userManager
    defaults:
        _controller: MainBundle:Admin:userManager
    requirements:
        _locale: en|fr
