main_home:
    path:     /
    defaults:
        _controller: MainBundle:Main:home
    requirements:
        _locale: en|fr

main_wall:
    path:     /wall
    defaults:
        _controller: MainBundle:Main:wall
    requirements:
        _locale: en|fr

main_unloggedWall:
    path:     /unWall
    defaults:
        _controller: MainBundle:Main:unloggedWall
    requirements:
        _locale: en|fr

main_search:
    path:     /search
    defaults:
        _controller: MainBundle:Main:search
    requirements:
        _locale: en|fr

main_add_favoris:
   path:     /favoris/add/{idSerie}
   defaults:
       _controller: MainBundle:Main:favoris
   requirements:
       _locale: en|fr

main_remove_favoris:
    path:     /favoris/remove/{idFavoris}
    defaults:
        _controller: MainBundle:Main:favoris
    requirements:
        _locale: en|fr

main_favoris:
    path:     /favoris
    defaults:
        _controller: MainBundle:Main:favoris
    requirements:
        _locale: en|fr

main_serie:
    path:     /serie/{idSerie}
    defaults:
        _controller: MainBundle:Main:serie
    requirements:
        idSerie: '[a-zA-Z-0-9]{36}'
        _locale: en|fr

main_episode:
    path:     /serie/{idSerie}/episode/{idEpisode}
    defaults:
        _controller: MainBundle:Main:episode
    requirements:
        idSerie: '[a-zA-Z-0-9]{36}'
        idEpisode: '[a-zA-Z-0-9]{36}'
        _locale: en|fr

main_pdf:
    path: /userGuide
    defaults:
        _controller: MainBundle:Main:pdf

main_account:
    path:     /account
    defaults:
        _controller: MainBundle:Main:account
    requirements:
        _locale: en|fr

main_account_change_password:
    path:     /account/password_change
    defaults:
        _controller: MainBundle:Main:account
    requirements:
        _locale: en|fr

main_account_change_user_information:
    path:     /account/change_user_information
    defaults:
        _controller: MainBundle:Main:account
    requirements:
        _locale: en|fr

main_legal:
    path:     /legal
    defaults:
        _controller: MainBundle:Main:legal
    requirements:
        _locale: en|fr

admin_modifSerie:
    path:     /admin/modifSerie
    defaults:
        _controller: MainBundle:Admin:modifSerie
    requirements:
        _locale: en|fr

admin_submitSerie:
    path:     /admin/submitSerie
    defaults:
        _controller: MainBundle:Admin:submitSerie
    requirements:
        _locale: en|fr

admin_validCritic:
    path:     /admin/validCritic
    defaults:
        _controller: MainBundle:Admin:validCritic
    requirements:
        _locale: en|fr

admin_userManager:
    path:     /admin/userManager
    defaults:
        _controller: MainBundle:Admin:userManager
    requirements:
        _locale: en|fr
