main_home:
    path:     /
    defaults:
        _controller: MainBundle:Main:home

main_wall:
    path:     /wall
    defaults:
        _controller: MainBundle:Main:wall

main_unloggedWall:
    path:     /unWall
    defaults:
        _controller: MainBundle:Main:unloggedWall

main_search:
    path:     /search
    defaults:
        _controller: MainBundle:Main:search

main_favoris:
    path:     /favoris
    defaults:
        _controller: MainBundle:Main:favoris

main_serie:
    path:     /serie/{idSerie}
    defaults:
        _controller: MainBundle:Main:serie
    requirements:
        page: '[a-zA-Z0-9]+'